name = "loom-scheduler"
main = "src/index.ts"
compatibility_date = "2024-12-28"

[[d1_databases]]
binding = "DB"
database_name = "loom-db"
database_id = "005a7ba7-e776-416d-b8be-4638144e86c2"

[[services]]
binding = "PROCESSOR"
service = "loom-processor"

[triggers]
crons = ["*/15 * * * *"]
